const size = {
    mobileXXS: '200px',
  mobileXS: '300px',
  mobileS: "319px",
  mobileS_M: "340px",
  mobileM: "375px",
  mobileSM: '390px',
  mobileL: "425px",
  tablet: "768px",
  laptop: "1014px",
  laptopM: "1020px",
  laptopL: "1440px",
  desktop: "2560px",
}

export const device = {
    mobileXXS: `(min-width: ${size.mobileXXS})`,
    mobileXS: `(min-width: ${size.mobileXS})`,
  mobileS: `(min-width: ${size.mobileS})`,
  mobileS_M:`(min-width: ${size.mobileS_M})`,
  mobileM: `(min-width: ${size.mobileM})`,
  mobileSM: `(min-width: ${size.mobileSM})`,
  mobileL: `(min-width: ${size.mobileL})`,
  tablet: `(min-width: ${size.tablet})`,
  laptop: `(min-width: ${size.laptop})`,
  laptopL: `(min-width: ${size.laptopL})`,
  laptopM:  `(min-width: ${size.laptopM})`,
  desktop: `(min-width: ${size.desktop})`,
  desktopL: `(min-width: ${size.desktop})`,
}
